name: depi_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  circular_profile_avatar: ^2.0.5
  http: ^1.5.0
  shimmer_animation: ^2.2.2
  dio: ^5.9.0
  provider: ^6.1.5+1
  badges: ^3.1.2
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  # firebase_core: ^4.1.1
  # firebase_auth: ^6.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_flavorizr: ^2.4.1

flutter:
  uses-material-design: true
  assets: 
    - assets/
